Linux 5.15.y/crocodile
hexagon-geo-surv/linux-leica pull request #48
Opened 2022-02-14 08:40 UTC by lidaide

I have test by these steps:
1. uname -a, it show "Linux crocodile 5.15.23-个1f8831b3194"
2. python3 wlan_ping.py will show OK
3. python3 bluetooth_scan.py will list bluetooth devices.

2022-03-02 07:10 UTC, htho-lgs requested changes

2022-03-02 07:10 UTC, htho-lgs commented on arch/arm64/configs/crocodile_defconfig
> +CONFIG_RFKILL=y
The description commit message is confusing:
- If you describe the configs, please refer to the help texts of them
- I does "we add the support to the Bluetooth device for MAYA-W1 serials, it was use High-Speed UART" mean?

2022-03-02 08:41 UTC, lidaide commented on arch/arm64/boot/dts/freescale/crocodile.dtsi
> +
have done by checkpath.pl tools.

2022-03-02 09:19 UTC, htho-lgs requested changes

2022-03-02 09:19 UTC, htho-lgs commented on arch/arm64/boot/dts/freescale/crocodile.dtsi
> +    usdhc1_pwrseq: usdhc1_pwrseq {
Still spaces

2022-03-02 09:19 UTC, htho-lgs commented on arch/arm64/boot/dts/freescale/crocodile.dtsi
> +    #size-cells = <0>;
Spaces

2022-03-02 09:29 UTC, lidaide commented on arch/arm64/boot/dts/freescale/crocodile.dtsi
> +    #size-cells = <0>;
have done

2022-03-07 08:19 UTC, zandrey approved these changes

2022-03-07 08:19 UTC, merged