Battery bq78z100
hexagon-geo-surv/linux-leica pull request #8
Opened 2020-12-21 11:23 UTC by Qingwu-Li

drivers:power:supply
--Add support for BQ27Z561, (cherry picked from commit 6f24ff9)
--Add support for BQ28z610, (cherry picked from commit 707d678)
--Add support for bq78z100 for Crocodile

Sorry for Closed the [PR7](https://github.com/hexagon-geo-surv/linux-leica/pull/7) and can not reopen.

2020-12-21 11:23 UTC, Qingwu-Li commented
@zandrey @grembeter, Thanks a lot for input and knowlage share, I split into 3 comments, device tree and deconfig will checkin later, this PR just battery driver relevant.

2020-12-21 12:41 UTC, zandrey commented
@Qingwu-Li Please see my comment in https://github.com/hexagon-geo-surv/linux-leica/pull/7#pullrequestreview-556249386 regarding the commit you've introduced - it should be prepared to be upstreamed.

2020-12-22 05:43 UTC, Qingwu-Li commented
@zandrey, OK, I'm working on prepare the patchs.

2020-12-22 11:44 UTC, zandrey requested changes
There are style problems with commit a97f194df44b2a34c56056b60869320b764c8a5b, please run `./scripts/checkpatch.pl` and have them fixed.

In addition, as the new `ti,bq78z100` is introduced - a separate documentation patch would be required here, see [Documentation/devicetree/bindings/submitting-patches.txt](../../../blob/stable/linux-5.4.y/Documentation/devicetree/bindings/submitting-patches.txt)

2020-12-22 11:44 UTC, zandrey commented on drivers/power/supply/bq27xxx_battery.c
> + * https://www.ti.com/product/BQ78Z100
Please use all small letters here (same as for all links above).

2020-12-23 06:22 UTC, Qingwu-Li commented
@zandrey @grembeter This patch can not upstream to master, since there are big difference.  I prepared another branch, it can be upstream to master, but can not build in Crocodile, due to the head file of 'include/linux/device.h', (new function dev_err_probe) the change and also introduced by many drivers, an also the documents changed to yaml in the master.
[The link of another branch picked from master.](https://github.com/hexagon-geo-surv/linux-leica/compare/hexagon-geo-surv:leica/5.4-2.1.x-imx/crocodile...Qingwu-Li:power_supply_master)

2021-04-09 04:18 UTC, Qingwu-Li commented
This PR expired, the change was upsteam to master.

2021-04-09 04:18 UTC, closed without merging